name: Build and Deploy React App # Name of the workflow (visible in GitHub Actions UI)

on: # Trigger events
  push:
    branches:
      - master # Runs on push to master
  pull_request:
    branches:
      - master # Runs on pull request to master

jobs:
  build: # Job name
    runs-on: ubuntu-latest # OS for the job

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18' # Node.js version

      - name: Install Dependencies
        run: npm install

      - name: Build React App
        run: npm run build

      - name: Setup SSH Key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.PRIVATE_SSH_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.DROPLET_HOST }} >> ~/.ssh/known_hosts

      - name: Deploy Build Using Rsync
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.DROPLET_HOST }}
          username: dev
          key: ${{ secrets.PRIVATE_SSH_KEY }}
          script: |
            rsync -avz --delete ~/dist/ dev@${{ secrets.DROPLET_HOST }}:/var/www/react-app/

      - name: Restart Nginx
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.DROPLET_HOST }}
          username: dev
          key: ${{ secrets.PRIVATE_SSH_KEY }}
          script: sudo systemctl restart nginx
